name: React Build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.1
    - name: Install and build application
      run: |
        npm install 
        npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

  deploy:
    name: Deploy to Google Cloud CDN
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Test 
      run: ls -la

    - name: Setup gcloud Authentication
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_ENCODED_API_KEY_LIMEBREW_DEV }}'

    - name: 'Set up Cloud CLI'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Deploy to Google Cloud CDN
      run: |
        gcloud config set project ${{ secrets.GCLOUD_DEPLOYMENT_PROJECT_ID }}
        cd build/
        gsutil -m cp -r . gs://${{ secrets.GCLOUD_DEPLOYMENT_BUCKET_NAME }}
  
     

      
        

      
    
    

            