name: React Build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.1
    - name: Install and build application
      run: |
        npm install 
        npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

  deploy:
    name: Deploy to Google Cloud CDN
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    
    steps:

    - name: Initialize Submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Test 
      run: ls -la
        

      
    
    

            