name: React Google CDN CI/CD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
    
        steps:
            - uses: actions/checkout@v3
            - name: Setup Nodejs
			  uses: actions/setup-node@v2
			  with:
				node-version: 18.16.1
			- name: Install and build applications
			  run: npm install && npm run build

            